### ISSUE TITLE
convert cf-create-user to a plugin

### ISSUE THREAD

**Issue by afeld** [18F/cloud-foundry-scripts#1]
...maybe? As suggested in https://github.com/18F/cloud-foundry-notes/pull/22#issuecomment-83139912.

* http://docs.cloudfoundry.org/devguide/installcf/use-cli-plugins.html
* https://github.com/cloudfoundry/cli/tree/master/plugin_examples

**Comment by ozzyjohnson** [comment]
That's the plan! 

My Go is sorely lacking but it seems straightforward to accomplish what all it's doing now.

**Comment by mogul** [comment]
Already done in https://github.com/18F/cf-provision-user-space-plugin
